name: Test Main Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build: 

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java-version: [ '11', '17', '21', '22' ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v3

    - name: Check dependencies
      run: ./gradlew dependencies

    - name: Build with Gradle
      run: ./gradlew assemble
      
    - name: Run unit tests
      run: ./gradlew test
